"""add events and candidate.event_id

Revision ID: 3758779afc2b
Revises: aafeeae27856
Create Date: 2026-01-25 14:36:09.241034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3758779afc2b'
down_revision: Union[str, Sequence[str], None] = 'aafeeae27856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('candidates', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'event_id')
    op.drop_table('events')
    # ### end Alembic commands ###
