"""event memberships + organizer + user votes

Revision ID: cc9dcbddc30d
Revises: 3758779afc2b
Create Date: 2026-01-25 15:16:24.717000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9dcbddc30d'
down_revision: Union[str, Sequence[str], None] = '3758779afc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user')
    )
    # Add as nullable first to handle existing rows, then backfill and enforce NOT NULL
    op.add_column('events', sa.Column('organizer_user_id', sa.String(length=255), nullable=True))
    op.execute("UPDATE events SET organizer_user_id = 'dev-user' WHERE organizer_user_id IS NULL")
    op.alter_column('events', 'organizer_user_id', nullable=False)

    op.add_column('submissions', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.execute("UPDATE submissions SET user_id = 'dev-user' WHERE user_id IS NULL")
    op.alter_column('submissions', 'user_id', nullable=False)

    op.add_column('submissions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_candidate_user_vote', 'submissions', ['candidate_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candidate_user_vote', 'submissions', type_='unique')
    op.drop_column('submissions', 'updated_at')
    op.drop_column('submissions', 'user_id')
    op.drop_column('events', 'organizer_user_id')
    op.drop_table('event_memberships')
    # ### end Alembic commands ###
